### ISSUE TITLE
Strctured NER - Address Extraction

### ISSUE THREAD

**Issue by raghavkhamar-stride** [strideai/PROJ_Address_Extraction#1]
# Objective
Address Extraction for Digital PDF documents.
# Important Links
- QA Report - https://docs.google.com/document/d/188vKCWxumzuqz_3SMvWX-plJOAYLA0hzMjmhiCsH1ko/edit?usp=sharing
- Approach Document - https://docs.google.com/document/d/1pEYSVhjOWpPiZUfnS8QQPZPgKLMbOl2a/edit
# Tasks
- [x] Development
- [x] Developer Tests
- [x] Resolving identified bugs
- [x] Hosting

**Comment by sahilStride** [comment]
API hosted at http://65.2.145.213:5005/

1. GIT REPO: https://github.com/strideai/PROJ_Address_Extraction
2. BRANCH: main
3. COMMIT ID: c865241
4. PROJECT NAME: Structured NER - Address Extraction

**Comment by sahilStride** [comment]
All testing was completed successfully.

Test report: https://docs.google.com/document/d/1BqWrMlEUiw8yrT3okkQfKDTDl6NlfsBq9O5CSNH9i3Y/edit?usp=sharing

**Comment by raghavkhamar-stride** [comment]
Thanks Sahil, Gautam and Jay. You can start with your new project. I will start assigning you tasks.
